import Head from "next/head";
import { useState } from "react";
import Navbar from "@/components/Navbar";
import Main from "@/components/Main";
import About from "@/components/About";
import Skills from "@/components/Skills";
import Projects from "@/components/Projects";
import Contact from "@/components/Contact";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div >
      <Head>
        <title>Alex Nguyen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white  dark:bg-gray-900 px-10 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <Main />
        </section>
        <About />
        <Skills />
        <Projects />
        <Contact />
      </main>
    </div>
  );
}
